#!/usr/bin/env python3

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import sys

def main():
    input = sys.stdin.buffer.read()
    fmtstring = "'"
    args = []
    nzeros = 0
    for i, c in enumerate(input):
        if c == ord('0'):
            nzeros += 1
            continue
        else:
            if nzeros < 5:
                fmtstring += nzeros * '0'
            else:
                fmtstring += '%0{n}d'.format(n=nzeros)
            nzeros = 0
        if c < 0x20 or c >= 0x7F or c == 0x27:  # non-printable; apostrophe
            if c >= 0o100:
                ndigits = 3
            elif i + 1 < len(input) and ord('0') <= input[i + 1] <= ord('7'):
                ndigits = 3
            elif c >= 0o10:
                ndigits = 2
            else:
                ndigits = 1
            fmtstring += '\\{c:0{w}o}'.format(c=c, w=ndigits)
            continue
        if i == 0 and c == 0x2D:  # leading hyphen-minus
            fmtstring += '%s'
            args += ['-']
            continue
        if c in {0x25, 0x5C}:  # percent; backslash
            fmtstring += chr(c) * 2
            continue
        fmtstring += chr(c)
    if nzeros < 5:
        fmtstring += nzeros * '0'
    else:
        fmtstring += '%0{n}d'.format(n=nzeros)
    fmtstring += "'"
    print('printf', fmtstring, *args)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
